In [1]:
import numpy as np

In [2]:
a = np.arange(1,28).reshape(3,3,3)#.transpose(0,2,1)
b = np.arange(1,7).reshape(3,2)#.transpose(0,2,1)

In [5]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [9]:
a.mean(axis=(0,1)).shape

(3,)

In [10]:
a.mean(axis=(0,1),keepdims=True).shape

(1, 1, 3)

In [13]:
for k in iter((1,2) for i in range(0, 10, 2)):
    print(k)

(1, 2)
(1, 2)
(1, 2)
(1, 2)
(1, 2)


In [43]:
a.sum(axis=(0,1))

array([117, 126, 135])

In [48]:
a.sum(keepdims=2)

array([[[378]]])

In [2]:
a = {2:2,9:3}

In [6]:
a[9]

3

In [9]:
np.logspace(-4, 0, num=20)

array([1.00000000e-04, 1.62377674e-04, 2.63665090e-04, 4.28133240e-04,
       6.95192796e-04, 1.12883789e-03, 1.83298071e-03, 2.97635144e-03,
       4.83293024e-03, 7.84759970e-03, 1.27427499e-02, 2.06913808e-02,
       3.35981829e-02, 5.45559478e-02, 8.85866790e-02, 1.43844989e-01,
       2.33572147e-01, 3.79269019e-01, 6.15848211e-01, 1.00000000e+00])