In [1]:
import numpy as np

In [2]:
np.zeros(3)

array([0., 0., 0.])

In [6]:
x = np.arange(12).reshape(12,1)
# np.prod(np.array(x.shape)[0,2])
np.std(x,axis=(0,1)).shape

()

In [9]:
a,b,c = [1,2]+[3]

In [5]:
ps[t][targets[t],0]

IndexError: index 3 is out of bounds for axis 1 with size 1

In [21]:
np.std(x,axis=0)

array([0.2351432 , 0.52271994, 0.18778653])

In [22]:
np.var(x,axis=0)

array([0.05529233, 0.27323613, 0.03526378])

In [28]:
np.random.random?
# (x.shape,seed=12).shape

In [30]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [49]:
x = x#.reshape(2,2,3)
x
# x.sum(axis=(0,1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
np.max(x, axis=1)

array([ 3,  7, 11])

In [25]:
for i in range(1,80):
    if 169%i == 0:
        print(i)

1
13
