In [2]:
import numpy as np

In [9]:
a = np.arange(1,13).reshape(4,3)#.transpose(0,2,1)
b = np.arange(1,7).reshape(3,2)#.transpose(0,2,1)

In [22]:
np.mean(a,axis=1,keepdims=True)

array([[ 2.],
       [ 5.],
       [ 8.],
       [11.]])

In [16]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [86]:
m = np.array([1,3,5,2])
np.argsort(m)

array([0, 3, 1, 2], dtype=int64)

In [75]:
a[:,0].reshape((a[:,0].shape[0],-1))

array([[1],
       [4]])

In [77]:
a[:,0][:,np.newaxis]

array([[1],
       [4]])