In [1]:
import numpy as np

In [43]:
x = np.arange(6).reshape((2,3))

In [52]:
x - np.sum(x, axis=1)[:,np.newaxis]

array([[-3, -2, -1],
       [-9, -8, -7]])

In [27]:
np.argmax(x,axis=1)

array([2, 2])

In [22]:
x[np.arange(2),[2,1]]

array([2, 4])

In [41]:
x.squeeze()

array([[0, 1, 2],
       [3, 4, 5]])

In [42]:
x

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])