In [64]:
import numpy as np

In [79]:
w = np.ones((6))
# w[0] == np.ones(2)[0]
# a,b = np.split(w,2)
a = w[:3].copy()

In [80]:
w

array([1., 1., 1., 1., 1., 1.])

In [77]:
w

array([1., 1., 1., 1., 1., 1.])

In [66]:
w= np.squeeze(w)
# w = np.expand_dims(w,axis=1)
np.mean(w,axis=1).shape

IndexError: tuple index out of range

In [69]:
np.split?

In [71]:
w

array([1., 1., 1., 1., 1., 1.])

In [54]:
np.array([1,1])

array([1, 1])

In [31]:
w[x, :]

IndexError: arrays used as indices must be of integer (or boolean) type